
ALTER TABLE CADASTRO.PESSOA_FISICA ADD CONSTRAINT FK_PESSOA_FISICA_PESSOA FOREIGN KEY (PESSOA_ID) REFERENCES CADASTRO.PESSOA (PESSOA_ID);

ALTER TABLE CADASTRO.PESSOA_JURIDICA ADD CONSTRAINT FK_PESSOA_JURIDICA_PESSOA FOREIGN KEY (PESSOA_ID) REFERENCES CADASTRO.PESSOA (PESSOA_ID);

ALTER TABLE CADASTRO.PESSOA_EMAIL ADD CONSTRAINT FK_PESSOA_EMAIL_PESSOA FOREIGN KEY (PESSOA_ID) REFERENCES CADASTRO.PESSOA (PESSOA_ID);

ALTER TABLE CADASTRO.PESSOA_EMAIL ADD CONSTRAINT FK_PESSOA_EMAIL_EMAIL FOREIGN KEY (EMAIL_ID) REFERENCES CADASTRO.EMAIL (EMAIL_ID);

ALTER TABLE CADASTRO.PESSOA_TELEFONE ADD CONSTRAINT FK_PESSOA_TELEFONE_PESSOA FOREIGN KEY (PESSOA_ID) REFERENCES CADASTRO.PESSOA (PESSOA_ID);

ALTER TABLE CADASTRO.PESSOA_TELEFONE ADD CONSTRAINT FK_PESSOA_TELEFONE_TELEFONE FOREIGN KEY (TELEFONE_ID) REFERENCES CADASTRO.TELEFONE (TELEFONE_ID);

ALTER TABLE CADASTRO.PESSOA_ENDERECO ADD CONSTRAINT FK_PESSOA_ENDERECO_PESSOA FOREIGN KEY (PESSOA_ID) REFERENCES CADASTRO.PESSOA (PESSOA_ID);

ALTER TABLE CADASTRO.PESSOA_ENDERECO ADD CONSTRAINT FK_PESSOA_ENDERECO_ENDERECO FOREIGN KEY (ENDERECO_ID) REFERENCES CADASTRO.ENDERECO (ENDERECO_ID);

ALTER TABLE CADASTRO.RESPONSAVEL ADD CONSTRAINT FK_RESPONSAVEL_PESSOA FOREIGN KEY (PESSOA_ID) REFERENCES CADASTRO.PESSOA (PESSOA_ID);

ALTER TABLE CADASTRO.MOTORISTA ADD CONSTRAINT FK_MOTORISTA_PESSOA FOREIGN KEY (PESSOA_ID) REFERENCES CADASTRO.PESSOA (PESSOA_ID);

ALTER TABLE CADASTRO.PROPRIETARIO ADD CONSTRAINT FK_PROPRIETARIO_PESSOA FOREIGN KEY (PESSOA_ID) REFERENCES CADASTRO.PESSOA (PESSOA_ID);

ALTER TABLE CADASTRO.VEICULO ADD CONSTRAINT FK_VEICULO_PROPRIETARIO FOREIGN KEY (PROPRIETARIO_ID) REFERENCES CADASTRO.PROPRIETARIO (PROPRIETARIO_ID);

ALTER TABLE CADASTRO.VEICULO ADD CONSTRAINT FK_VEICULO_RESPONSAVEL FOREIGN KEY (RESPONSAVEL_ID) REFERENCES CADASTRO.RESPONSAVEL (RESPONSAVEL_ID);

ALTER TABLE CADASTRO.PERMISSAO_DIRIGIR ADD CONSTRAINT FK_PERMISSAO_DIRIGIR_MOTORISTA FOREIGN KEY (MOTORISTA_ID) REFERENCES CADASTRO.MOTORISTA (MOTORISTA_ID);

ALTER TABLE CADASTRO.PERMISSAO_DIRIGIR ADD CONSTRAINT FK_PERMISSAO_DIRIGIR_VEICULO FOREIGN KEY (VEICULO_ID) REFERENCES CADASTRO.VEICULO (VEICULO_ID);